modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="gamemaster" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Game Master" #mandatory
updateJSONURL="https://minecraft.sweetrpg.com/gamemaster/updates.json" #optional
displayURL="https://minecraft.sweetrpg.com/gamemaster/" #optional
logoFile="gamemaster.png" #optional
credits="TBD" #optional
authors="Paul Schifferer" #optional
description='''
TBD
'''

[[dependencies.gamemaster]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.gamemaster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
