modLoader="javafml"
loaderVersion="${fml_version_range}"
license="MIT"
issueTrackerURL="https://github.com/sweetrpg/GameMaster/issues"
displayURL="https://minecraft.curseforge.com/projects/gamemaster/"
logoFile= "gm_logo.png"

[[mods]]
modId="gamemaster"
version="${version}"
updateJSONURL="https://minecraft.sweetrpg.com/mods/gamemaster/version.json"
displayName="Gamemaster"
credits="paulyhedral"
authors="paulyhedral"
description='''
    Take control of the world!
    '''

[[dependencies.gamemaster]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.gamemaster]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.gamemaster]]
modId="configured"
mandatory=false
versionRange="[1.5.4,)"
ordering="NONE"
side="BOTH"

[modproperties.configured]
catalogueImageIcon="configured_icon.png"
configuredBackground="minecraft:textures/block/gray_wool.png"
